services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context:  requirements/mariadb
    image:  mariadb
    restart:  always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    networks:
      - inception
    build:
      context:  requirements/nginx
    image:  nginx
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  always
    ports:
      - "443:443"

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    networks:
      - inception
    build:
      context:  requirements/wordpress
    image:  wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  always
    ports:
      - 9000:9000
   
networks:
    inception:
      driver: bridge

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'