services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context:  requirements/mariadb
    image:  mariadb
    restart:  always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context:  requirements/nginx
    image:  nginx
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  always
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    build:
      context:  requirements/wordpress
  #     args:
  #       - SQL_DATABASE
  #       - SQL_USER
  #       - SQL_PASSWORD
  #       - DOMAIN_NAME
  #       - SITE_TITLE
  #       - ADMIN_USER
  #       - ADMIN_PASS
  #       - ADMIN_EMAIL
  #       - USER0_LOGIN
  #       - USER0_MAIL
  #       - USER_PASS
    image:  wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart:  always
    ports:
      - 9000:9000
   
networks:
    inception:
      driver: bridge

volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'